### PR TITLE
Allow passing `highlightDateContainerStyle` as a prop

### PR DESCRIPTION
**Pull request by dezse97**
Solves #259 :)

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @dezse97 for adding this prop. I'll make some minor changes (code styling, remove version bump etc).

**Comment by peacechen** [comment]
@dezse97 
Please test your fork after the changes I made. There was a logic error in the changes to `_dateViewStyle` that prevented the animation on the selected date.

**Comment by dezse97** [comment]
Thank you for the changes and the quick review @peacechen. Yes, it's working fine after your changes as well. :) It can be merged from my side.

**Comment by ysmike** [comment]
Is this prop working for v2.1.5? @peacechen @dezse97

**Comment by peacechen** [comment]
Published in 2.1.6
I was waiting on other changes in the works, but it sounds like you need this feature now.

**Comment by ysmike** [comment]
Thank you! @peacechen
It looks like `dayContainerStyle` overrides `highlightDateContainerStyle`. Is this the expected behavior? I'd like to style all the days of the week with a different styling for the selected date.

**Comment by peacechen** [comment]
The current code does have `dayContainer` style overriding the others:
https://github.com/BugiDev/react-native-calendar-strip/blob/49ecc6f5039b40eb39fa243f4b850d7a330c3391/src/CalendarDay.js#L468

`highlightDateContainerStyle` should probably take precedence. Hopefully no one is using both. Would you mind testing it with `_dateViewStyle` and `dayContainerStyle` flipped in the day component above?

**Comment by ysmike** [comment]
If flipped, background color of the `dayContainerStyle` doesn't apply. Other props passed to `dayContainerStyle` does apply though.

**Comment by QuintonC** [comment]
Jumping in here as I am using both (see attached screenshot):

Any way that we can get an update worked on for this? Seems kind of stale given that this was posted in February.

Day - Empty State

**Pull request merged**
