### PR TITLE
fix(issue 306) library causing crash to the app due to rlv not defined.

### PR DESCRIPTION
**Pull request by adamgajzlerowicz**
Simplified version of this pr
https://github.com/BugiDev/react-native-calendar-strip/pull/322

### CODE REVIEW

**Comment by joeljoeljoeljoel** [comment]
Can this please be approved? We're wating eagerly :)

**Comment by jeffreyvanhees** [comment]
Can somebody of the contributors approve this PR? My app is still crashing because of this bug.

**Comment by joeljoeljoeljoel** [comment]
Is this library not maintained anymore?

**Comment by esWeborg** [comment]
Please accept this PR

**Comment by YisusJe** [comment]
Waiting for it too

**Comment by peacechen** [comment]
Thanks @adamgajzlerowicz !

The original author of this library is AWOL and I haven't been able to get in touch with him to add more maintainers. Could use some help here.

**Comment by trongtv147** [comment]
My app crashes when downloaded from App Store, Play Store and APK but it runs fine locally (npm run). How can it be fixed? Thanks

**Comment by peacechen** [comment]
Your question is off topic for this PR. Search the issues and the Readme. Your issue may be related to localization:
https://github.com/BugiDev/react-native-calendar-strip#build-release-info

**Pull request merged**
