### PR TITLE
Fixed custom fontSize for day

### PR DESCRIPTION
**Pull request by IronTony**
I have inverted the params because in the old way the fontSize was overwritten by the component props/state

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks for the PR.  This looks ok, though I'm concerned it may change behavior for existing users.  If I understand it correctly, you want to set `fontSize` in the `customDatesStyles` prop and override the built-in scaling?

**Comment by IronTony** [comment]
I think it is a bug because as you can see some lines below the 2 params are inverted.
If I try to set in my style the fontSize it doesn't affect the day name, instead if you test with the inverted params (as in my PR), the user fontSize wins and it is set correctly.

Screenshot 2019-08-08 at 22 26 02

**Comment by peacechen** [comment]
You're right, that looks like the proper fix.  Should `dateNumberStyle` also be placed ahead of the state's fontSize?

**Comment by IronTony** [comment]
The right position is the one of the image above. `dateNumberStyle` and `dateNameStyle` have to be in second position.
Here is a quick recap:

```
style={[{ fontSize: this.state.dateNameFontSize }, dateNameStyle]}
style={[{ fontSize: this.state.dateNumberFontSize }, dateNumberStyle]}
```
In this way the user style will override the default font size ;)

**Comment by peacechen** [comment]
I totally overlooked that. Thanks for clarifying 👍

**Pull request merged**
