### PR TITLE
update styling to be top-aligned for the days row

### LINKED ISSUE #148: Marked dates cause dates to not be aligned correctly
When marking some dates using the `markedDates` prop, the dots result in the day names/numbers not being aligned. Is there a way to set the styling for the day list to fix this, or any ideas what I'm doing wrong? See attached screenshot.
Screen Shot 2019-09-29 at 9 59 18 AM

### PR DESCRIPTION
**Pull request by sam1463**
Resolves #148

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @sam1463 👍 

I'll publish later today when I have access to my computer.  In the meantime, does this cause any side-effects, particularly when not using the dots?  I vaguely recall a past discussion where the dates are shifted up compared to before, potentially causing an issue with custom date styles.
https://github.com/hellpirat/react-native-calendar-strip#customdatesstyles

**Comment by peacechen** [comment]
@sam1463  Please validate that custom dates styles is rendered correctly with your changes.  I'll merge as soon as that's confirmed.

**Comment by sam1463** [comment]
I probably won't have time until this weekend. I'll tag Juuso from the issue, in case he wants the fix sooner and has time to verify whether it works with custom styles.

**Comment by peacechen** [comment]
Tip: to test Sam's fork, use this format in the package.json:
```
{
  "dependencies": {
    "react-native-calendar-strip": "https://github.com/sam1463/react-native-calendar-strip"
  }
}

**Comment by JuusoPalander** [comment]
This seems to fix the alignment issue of days but the week switching icons are not aligned correctly vertically. But they can be aligned by setting `iconLeftStyle` and `iconRightStyle`.

**Comment by peacechen** [comment]
Thanks @JuusoPalander for testing it.  It would be ideal if iconLeftStyle and iconRightStyle were automatically adjusted when dots are used.

Were you able to test the custom date styles?  You can use the sample code to create and pass in the `customDatesStyles` prop.
```
  let customDatesStyles = [];
  let startDate = moment();
  for (let i=0; i<6; i++) {
    customDatesStyles.push({
        startDate: startDate.clone().add(i, 'days'), // Single date since no endDate provided
        dateNameStyle: styles.dateNameStyle,
        dateNumberStyle: styles.dateNumberStyle,
        // Random color...
        dateContainerStyle: { backgroundColor: `#${(`#00000${(Math.random() * (1 << 24) | 0).toString(16)}`).slice(-6)}` },
      });
  }

  render() {
    return (
      <CalendarStrip
        customDatesStyles={customDatesStyles}
        ...
      />
    );
  }
```

**Comment by lingeshwaran1912** [comment]
> This seems to fix the alignment issue of days but the week switching icons are not aligned correctly vertically. But they can be aligned by setting `iconLeftStyle` and `iconRightStyle`.

How to fix the bug. Can you send your code

**Comment by peacechen** [comment]
The root of the problem is that marked dot dates have an extra component underneath.  This causes a problem when centering the content in the day container.
Changing that to flex-start is an option, but causes side-effects due to shifting the content.

The optimal fix is to include an empty dots container for dates that don't have dots.  See commit 2f437364e1f5ff1b4614fef29a5f4529088815ab.
This will be published in 1.4.0

**Pull request closed without merging**
