### PR TITLE
Added props to style todays date differently

### PR DESCRIPTION
**Pull request by samcolby**
Added a todayDateNumberStyle and a todayDateNameStyle prop to add a different styling to todays date.  Similar to how apple does it in the Health App.

### CODE REVIEW

**Comment by peacechen** [comment]
Sam, thanks for the PR.  Similar to #33 where method calls were moved out of the render loop for CalendarStrip.js, we should do the same for CalendarDay.js.

I propose moving the `isToday()` call from render() to a new `updateDayData()` method.  `updateDayData()` would set a state variable `isToday` that holds the precomputed value of whether the day is today.  

That allows render() to simply reference `this.state.isToday` instead of making an expensive (and often unnecessary) method call every render loop.

I could begin refactoring the existing CalendarDay.js code and you could update this PR after, or if you're up to the task, create a PR that refactors everything.

**Comment by samcolby** [comment]
Hi, 

I did think moving that out of the render, but we would still need some way of updating 'today' if the component wasn't unmounted for more than 24 hours.  Today isn't always going to be the same value for the life of the mounted component.

Really not sure of the best way to solve that, but given we're only talking milliseconds for each isToday call, I wasn't sure it was worth it.  As per my other comment, we'd be much better off just controlling how often each CalendarDay re renders.  

Does that make some sense?

**Comment by peacechen** [comment]
My first thought for the long-running case would be to hook into componentWillReceiveProps, but that may not guarantee it would update when the day changes.  Will have to mull over this.

I've found it difficult to control when React re-renders.  We could use componentShouldUpdate which introduces its own complexity.  Would like to hear your ideas on that.

**Comment by peacechen** [comment]
After our performance discussions, what changes would you recommend here?

**Comment by samcolby** [comment]
Hi,

I did setup a scrollview with 120 of these in to see how bad performance was, but haven't tried it with these changes yet. Does this change impact on performance as it is?  

I do still think getting better control of your setState calls will give you your biggest performance improvements though.  I can raise an issue with some thoughts about that to discuss if you like.

As for this PR, I guess we could pass 'today' down from the CalendarStrip as a prop and then run the shouldComponentUpdate trick as with my other two components.  I think it is should also be possible to remove the state from CalendarDay too, which would also help. I'd need to look at it in a bit more detail though.

**Comment by peacechen** [comment]
Sorry this PR has been neglected for so long.  I'm not sure we fully resolved the performance implications of isToday().

The prop `customDatesStyles` has been added which allows the user to style any arbitrary date any way they want.  This could be used to style "today's" date.  The user would need to manage date/week boundary changes in this case.  Is it worth it to make CalendarStrip intelligent as far as keeping track of "today"?

**Comment by samcolby** [comment]
I just use my branch with this change in, so no hassle from me to include it.  The performance implications for one (or two) instances of the strip are not worth worrying about really, but I know you have many instances.

Feel free to just close this or keep open until we come up with a better solution


> Is it worth it to make CalendarStrip intelligent as far as keeping track of "today"?

For what it's worth, I do think this is something that should be included. I also think it would be nice to have a button to 'Go To Today', but that's possibly a separate issue.

**Comment by peacechen** [comment]
I suggest that we solve the issue of how to handle date/week boundary changes before pulling this in.  If CalendarStrip doesn't handle it, then the caller of this library needs to, in which case the caller might as well take care of `today's` styling.

How should date boundary changes be handled?  (when the clock changes from 11:59 pm to 12:00 am)

It could poll (bad), slow poll (e.g. every hour, a tradeoff that uses less resources but is inaccurate), or somehow get an event on a date change.

What if the clock is changed, either by the user or automatically from time server?

**Comment by peacechen** [comment]
The `customDatesStyles` prop is a more general way to highlight dates.  It can be used to style today like this:
```
let customDatesStyles = [];
customDatesStyles.push({
        startDate: moment(),
        dateNameStyle: {styles.someDateNameStyle},
        dateNumberStyle: {styles.someDateNumberStyle},
        dateContainerStyle: {styles.someDateContainerStyle},
    });
  }

  render() {
    return (
      <CalendarStrip
        customDatesStyles={customDatesStyles}
        ...
      />
    );
  }
```

This eliminates the need to maintain separate today styling props.  It also allows the user to decide what to do when the current date changes (date boundary corner cases).

A "Go to today" button would be useful.  Not sure where to place it, but please feel free to open a separate issue to discuss.

**Pull request closed without merging**
