### PR TITLE
Highlight date container style override fix

### PR DESCRIPTION
**Pull request by QuintonC**
Fixed issue where the highlightDateContainerStyle was overridden by dayContainerStyle. Also added dayContainerStyle to the list of valid props for the package.

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @QuintonC for these fixes 👍 

Please revert the version bump in package.json. That gets bumped in a separate commit since there may be multiple commits in a release.

**Comment by QuintonC** [comment]
> Thanks @QuintonC for these fixes 👍
> 
> Please revert the version bump in package.json. That gets bumped in a separate commit since there may be multiple commits in a release.

Removed version bump.

Let me know if you need anything else or want eyes on another PR. Happy to help out since the project I'm working on will be using this package for the foreseeable future 👍

**Comment by peacechen** [comment]
Thanks. Submit as many PRs as needed for your usage. Search the issues to see if it also fixes a previously reported bug.

Do you need a new version published immediately?

**Comment by QuintonC** [comment]
> Thanks. Submit as many PRs as needed for your usage. Search the issues to see if it also fixes a previously reported bug.
> 
> Do you need a new version published immediately?

I don't need it published immediately. Maybe we can take care of some of the other PRs that are on here and then publish a new version.

Thanks for the merge 🙂

**Comment by peacechen** [comment]
Published in 2.2.5

**Pull request merged**
