### PR TITLE
Fix linting error

### PR DESCRIPTION
**Pull request by sugersuger**
[In this PR](https://github.com/BugiDev/react-native-calendar-strip/pull/242), we supported `externalScrollView` prop to replace ScrollView with something else.  

It's very useful, but `RecyclerListView` has many TypeScript-errors. Therefore, we have TypeScript linting-error again.  

We can't fix those errors directly.  
So I skip the Library's type-check by adding a file `tsconfig.json`.  

And I add some necessary Declaration Files.

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @sugersuger 
Is this ready to be published?

**Comment by sugersuger** [comment]
In my opinion, we might want to more check the `index.d.ts` file in our project over for potential TypeScript-problems before publishing.  
This PR only fix compile-errors if we run the `$ tsc` command in our project's root directory.  

For example, if this branch is merged and the user uses this package, the user may see a type-problem.  
image  

I didn't change the `ReactNativeCalendarStrip` class's type annotation anything.  
Perhaps the error has potentially been in our project.

**Comment by peacechen** [comment]
Another PR has been in the pipeline waiting to be published. Is there a quick way to resolve the TS definition errors?

**Comment by sugersuger** [comment]
@peacechen 
I fix the TS definition errors.  
Anyhow, this revision is ready to be published.  
If any TS error is found, mention me anytime.

**Comment by peacechen** [comment]
@sugersuger Thanks again for contributing to this project 🎉

**Pull request merged**
