### PR TITLE
More customization options for CalendarHeader

### PR DESCRIPTION
**Pull request by ruslanchek**
- Property calendarHeaderPosition added (above | below).
- Property calendarHeaderContainerStyle added.
- CalendarHeader now has Text wrapped into View for more customization flexibility.

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @ruslanchek for the useful new features.  Please update the Readme with the new props and I'll merge.

**Comment by ruslanchek** [comment]
Done. Please check the readme.

**Comment by peacechen** [comment]
Thanks for updating the Readme.  Just curious, is prettier resizing the prop columns, or are you doing that manually?  Makes the diff much bigger and difficult to see exactly what changed.

**Comment by mbrtn** [comment]
OMG that’s prettier, sorry. I can fix it :-)

**Comment by ruslanchek** [comment]
OMG that’s prettier sorry. I can fix it :-)

**Comment by ruslanchek** [comment]
Done

**Comment by ruslanchek** [comment]
I've also updated index.d.ts

**Comment by peacechen** [comment]
Great work. Thanks again @ruslanchek 👍

**Comment by ruslanchek** [comment]
Thank you! Could you also publish new package?

**Comment by peacechen** [comment]
1.3.8 was published earlier this morning

**Pull request merged**
