### PR TITLE
Check if data is empty on visible indices changed (#236)

### PR DESCRIPTION
**Pull request by cc-matthias-m**
Hello,

This is a fix for the issue #236 .

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @cc-matthias-m

**Comment by cc-matthias-m** [comment]
Hello,

I wonder, when the next version 2.0.10, which include this PR, will be released.

Bye

**Comment by peacechen** [comment]
Apologies for the delay. Typescript errors were introduced and we're sorting those out. I'll publish 2.1.0 as soon as those are done.

**Comment by cc-matthias-m** [comment]
Hello,

It's a good news. Thanks for the answer.

**Comment by peacechen** [comment]
This fix has been published in 2.1.0.  Thanks for your contributions and patience

**Pull request merged**
