### PR TITLE
Feature: add marked dates

### PR DESCRIPTION
**Pull request by hellpirat**
Add feature for adding marked dates.

Usage example: 

```
markedDates={{
   '2018-12-03': { dots: [ { key: 1, color: 'red', selectedDotColor: 'blue' }, { key: 2, color: 'blue', selectedDotColor: 'red' } ] },
   '2018-12-04': { dots: [ { key: 3, color: 'green', selectedDotColor: 'blue' }, { key: 4, color: 'blue', selectedDotColor: 'red' } ] },
   '2018-12-05': { dots: [ { key: 5, color: 'white', selectedDotColor: 'blue' }, { key: 6, color: 'blue', selectedDotColor: 'red' } ] },
 }}
```

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @hellpirat for this handy feature.  Some suggestions:

1. Add a screenshot.  You can place one in this thread, then use the image link in the documentation.
2. For consistency with the rest of the library, `markedDates` should support any Moment paseable date value (string, Date or Moment object).
3. Change `markedDates` to an array of objects.  Each entry would contain a `date` key along with the `dots` key, enabling support for `#2` above.
3. Update `getDateMarking` to search the array for a matching date.  Parse and compare the date with Moment (e.g. `moment(date).isSame(day, 'day')`
4. Set the default prop value for `markedDates` to an empty array.  This reduces the error-checking code needed.

**Comment by hellpirat** [comment]
@peacechen Hi, I updated a code :) Please check it.

Usage example:

```
markedDates={[
  {
    date: '2018-12-26',
    dots: [
      { key: 1, color: 'red', selectedDotColor: 'blue' },
      { key: 2, color: 'blue', selectedDotColor: 'red' },
    ],
  },
  {
    date: '2018-12-28',
    dots: [
      { key: 1, color: 'red', selectedDotColor: 'blue' },
      { key: 2, color: 'blue', selectedDotColor: 'red' },
    ],
  },
  {
    date: moment(),
    dots: [
      { key: 1, color: 'red', selectedDotColor: 'blue' },
      { key: 2, color: 'blue', selectedDotColor: 'red' },
    ],
  },
]}
```

**Comment by hellpirat** [comment]
@peacechen 

image

**Comment by peacechen** [comment]
@hellpirat  Commits merged.  I'll publish on npm shortly.

The marked / unmarked dates don't center vertically.  It looks like you may need to add a blank spacer for dates that are unmarked, but only if the markedDates prop is provided.

**Pull request merged**
